spring.application.name: demo

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo-db
    username: demo-db
    password: 12345
  jpa:
    show-sql: true
